ecommerce_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: yourAccountId

      # User/password auth
      user: dbt_user
      password: yourPassword

      role: dbt
      database: TESTDB
      warehouse: SMALLWAREHOUSE
      schema: ECOMMERCE
      threads: 1
      client_session_keep_alive: False
      #query_tag: [anything]

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
