version: 2

sources:
  - name: ecommerceraw #name we would use to refer to this source
    schema: ECOMMERCE #Snowflake schema name where raw ECOMMERCE data is stored
    description: Raw Ecommerce data #data source desc. To be used in dbt documentation
    tables:
      - name: DATA #Snowflake table name where raw ECOMMERCE data is stored
        description: Merged invoice and invoice items data #table desc. To be used in dbt documentation